tasks:
  - name: open-readme
    command: gp open README.md
  - name: setup-api
    before: |
      cd /workspace/workshop-streaming-game/api
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    command: |
      cd /workspace/workshop-streaming-game/api
      echo -e "\n\n*** API READY TO START***\n"
  - name: setup-client
    before: |
      cd /workspace/workshop-streaming-game/client
      nvm install 16.11.1
      npm install -g npm@latest
      npm install astra-setup
      npm install
    command: |
      cd /workspace/workshop-streaming-game/client
      echo -e "\n\n*** CLIENT READY TO START***\n"
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 8000
    onOpen: ignore
    visibility: public
